### ISSUE TITLE
`Zyre.SetPort` not changing discovery port

### ISSUE THREAD

**Issue by lbergnehr** [NetMQ/Zyre#7]
When running something like this:

``` cs
var node = new Zyre("node", loggerDelegate: Console.WriteLine);
node.SetPort(9999);
node.Start();
node.Dump();
```

The following, among other things, is logged to the console:

```
- discovery=beacon port=5670 interval=00:00:00
```

The beacon port is not set according to the `SetPort` method, which, if I'm reading this correctly, can also be seen in the code, where the `_beaconPort` always uses the default value of `5670`.

Should [this line](https://github.com/NetMQ/Zyre/blob/c537f60560864b8342403fcf4387cb2436fa5326/src/NetMQ.Zyre/ZyreNode.cs#L364) set `_beaconPort` instead?

**Comment by dalebrubaker** [comment]
Absolutely correct, thanks for finding this. I'll do a pull request now and I'll try to update NuGet later today.

**Comment by lbergnehr** [comment]
@dalebrubaker did you get around to publishing this to nuget.org yet? Does it take some time for them to validate it as well? Thanks for doing it regardless if you found time for it just yet or not.

**Comment by dalebrubaker** [comment]
@lbergnehr 

Yes, I got this message back from them at 1:17 Eastern this afternoon. 
     "The package NetMQ.Zyre 1.0.0-beta was just published on NuGet Gallery"
But it doesn't seem to be "live" yet. AFAIK it will show up soon (no validation is needed).
Your welcome, and thank you again.

p.s. I just now checked and I can "see" it in Visual Studio. For some reason it still shows -rc1 as the latest prerelease, but 1.0.0-beta is also there.

**Comment by lbergnehr** [comment]
@dalebrubaker cool! The reason it shows `1.0.0-beta` as an earlier version to `1.0.0-rc1` I think is because nuget orders versions in alphabetic order (in the case where the version contains strings). That is: `1.0.0-a` is seen as an earlier version than `1.0.0-b`, regardless of when they were published to nuget.org.
